# Generated by Django 5.0.1 on 2024-02-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0005_servicios_idservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='idServicio',
        ),
    ]
