# Generated by Django 5.0.1 on 2024-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0007_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTicket', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descrip', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
