# Generated by Django 5.0.1 on 2024-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0008_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='nAbonado',
            field=models.IntegerField(default=0),
        ),
    ]
